categories:
  fe_change_pwd: ~

settings:
  fe_change_pwd.changePasswordPid:
    default: 0
    type: int
    category: fe_change_pwd
  fe_change_pwd.redirect.allAccessProtectedPages:
    default: true
    type: bool
    category: fe_change_pwd
  fe_change_pwd.redirect.includePageUids:
    default: ''
    type: string
    category: fe_change_pwd
  fe_change_pwd.redirect.includePageUidsRecursionLevel:
    default: 0
    type: int
    category: fe_change_pwd
  fe_change_pwd.redirect.excludePageUids:
    default: ''
    type: string
    category: fe_change_pwd
  fe_change_pwd.redirect.excludePageUidsRecursionLevel:
    default: 0
    type: int
    category: fe_change_pwd
